// Thread opt-out + auto-footer text contract. Pure, dependency-free, the
// single source of truth shared by message-sending and message-reading code
// so the appended footer and the strip-on-read can never drift apart.
//
// WHY a fixed code constant (not AI-composed): reliable stripping on read is
// only possible because the footer is byte-identical every time (only the
// hashtag varies). If the AI wrote the footer its wording would vary and no
// matcher could strip it. See the design spec for the full rationale.

// FROZEN MARKER — the strip matcher keys on this, NOT on the hashtag, so a
// future hashtag rename still strips old footers. The middle of the footer
// may be reworded across versions; this prefix must NEVER change, or footers
// written by older versions would stop being stripped.
const OPTOUT_FOOTER_PREFIX = "Auto-generated by lwchat";

// The footer is markdown-italic so it renders muted in Google Chat.
function buildFooter(hashtag) {
  return `_(${OPTOUT_FOOTER_PREFIX} — reply ${hashtag} to mute lwchat in this thread.)_`;
}

// Append the footer to a message body (body has already been mention-resolved;
// the footer has no @mentions so it must not go through that pass).
function appendFooter(text, hashtag) {
  return `${text}\n\n${buildFooter(hashtag)}`;
}

// A message opts the thread out ONLY if it is exactly the hashtag (trimmed,
// case-insensitive). Exact-match — not substring — so another lwchat user's
// footer (which contains the hashtag) never falsely mutes the thread.
function isOptOutMessage(text, hashtag) {
  return String(text ?? "").trim().toLowerCase() === (hashtag || "").toLowerCase();
}

function threadHasOptOut(messages, hashtag) {
  return (messages || []).some((m) => isOptOutMessage(m.text, hashtag));
}

// Remove a trailing auto-generated footer block from message text so the agent
// never sees the stray hashtag inside it. Anchored on the frozen prefix and
// the end of the string; lazy match expands to the final `)_`. Idempotent and
// safe on footer-less or empty input.
const FOOTER_RE = new RegExp(`\\n*_\\(${OPTOUT_FOOTER_PREFIX}[\\s\\S]*?\\)_\\s*$`, "u");
function stripAutoFooter(text) {
  return String(text ?? "").replace(FOOTER_RE, "").trim();
}

export {
  OPTOUT_FOOTER_PREFIX,
  buildFooter,
  appendFooter,
  isOptOutMessage,
  threadHasOptOut,
  stripAutoFooter,
};
